spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa: 
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  security:
    user:
      name: admin
      password: 123
      roles:
      - ADMIN
    oauth2:
      resource:
        jwt:
          keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
            -----END PUBLIC KEY-----

jwt:
  secret: MyScret